USE [master]
GO

/****** Object:  Database [BDSistemaProyectos]    Script Date: 14/05/2015 20:01:45 ******/
CREATE DATABASE [BDSistemaProyectos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDSistemaProyectos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BDSistemaProyectos.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BDSistemaProyectos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BDSistemaProyectos_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BDSistemaProyectos] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDSistemaProyectos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDSistemaProyectos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BDSistemaProyectos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BDSistemaProyectos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDSistemaProyectos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDSistemaProyectos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BDSistemaProyectos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDSistemaProyectos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDSistemaProyectos] SET  MULTI_USER 
GO

ALTER DATABASE [BDSistemaProyectos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDSistemaProyectos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDSistemaProyectos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDSistemaProyectos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BDSistemaProyectos] SET  READ_WRITE 
GO

