//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProyectos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistema
    {
        public Sistema()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string NombreError { get; set; }
        public int ValorDemora { get; set; }
        public int ValorPosible { get; set; }
        public int CalculoCategoria { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
